---
name: Checks

on: [push]

jobs: 
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login in docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test and Lint with Docker Compose
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: Lint with Docker Compose
        run: docker compose run --rm app sh -c "flake8 ."